# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0003_auto_20171109_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 9, 22, 10, 54, 753996)),
        ),
        migrations.AlterField(
            model_name='reclutado',
            name='rec_proyecto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reclutado',
            name='rec_proyecto_puesto',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
