# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0004_auto_20171109_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclutado',
            name='rec_proyecto',
        ),
        migrations.AddField(
            model_name='reclutado',
            name='rec_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 9, 22, 14, 49, 791904)),
        ),
        migrations.AlterField(
            model_name='reclutado',
            name='rec_proyecto_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Puesto'),
        ),
    ]
