# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0008_auto_20171109_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 9, 22, 32, 56, 876872)),
        ),
    ]
