# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0011_auto_20171110_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclutado',
            old_name='rec_proyecto_id',
            new_name='rec_proyecto',
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 10, 9, 8, 51, 386981)),
        ),
    ]
