# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0012_auto_20171110_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclutado',
            name='rec_proyecto',
        ),
        migrations.RemoveField(
            model_name='reclutado',
            name='rec_proyecto_puesto',
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 10, 9, 18, 41, 641664)),
        ),
    ]
