# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0013_auto_20171110_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclutado',
            name='rec_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclutado',
            name='rec_proyecto_puesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Puesto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 10, 10, 30, 23, 429650)),
        ),
    ]
