# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0015_auto_20171110_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 10, 11, 46, 26, 607703)),
        ),
    ]
