# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0016_auto_20171110_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 11, 20, 58, 7, 748708)),
        ),
        migrations.AlterField(
            model_name='reclutado',
            name='rec_email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
