# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0020_auto_20171115_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='proyecto_url',
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 25, 17, 19, 50, 158941)),
        ),
    ]
