# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0022_auto_20171125_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='proyecto_planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Planta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 25, 17, 24, 49, 438125)),
        ),
    ]
