# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0024_auto_20171125_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 25, 17, 46, 11, 433967)),
        ),
    ]
