# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0025_auto_20171125_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='planta_asignado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Planta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 25, 18, 3, 32, 774082)),
        ),
    ]
