# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0026_auto_20171125_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestaciones',
            name='prestacion_imagen',
            field=models.FileField(default=1, upload_to='Tecmaiconos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 25, 19, 8, 10, 479752)),
        ),
    ]
