# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0027_auto_20171125_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 1, 17, 7, 33, 390723)),
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_requeridos_posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TecmaMain.Puesto'),
        ),
    ]
