# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0028_auto_20171201_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 1, 17, 22, 6, 51323)),
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_requeridos_posicion',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
