# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecmaMain', '0034_auto_20171211_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sueldos',
            name='sueldos_total_efectivo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='metasreclutador',
            name='metas_fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 13, 15, 38, 16, 699598)),
        ),
    ]
